server {
    listen 127.0.0.1:8080;
    server_name localhost;
    access_log off;

    location = /nginx-health {
        default_type text/plain;
        return 200 "OK\n";
    }

    location / {
        return 404;
    }
}
