name: JBS-Nginx-Ultra-Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. 계정명을 강제로 소문자로 변환하여 환경 변수에 저장합니다.
      - name: Lowercase Repository Owner
        run: echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          # 2. 위에서 변환한 소문자 변수(env.OWNER_LC)를 사용합니다.
          tags: ghcr.io/${{ env.OWNER_LC }}/jbs-nginx:ultra-4.0
