name: JBS-Nginx-Ultra-Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'nginx/**' # nginx 폴더가 바뀔 때만 작동

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # GHCR에 쓰기 권한 부여
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # [중요] 계정명(TAE-OK-11)을 소문자(tae-ok-11)로 변환하는 단계
      - name: Lowercase Repository Owner
        run: echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          # 변환된 소문자 계정명(env.OWNER_LC)을 사용합니다.
          tags: ghcr.io/${{ env.OWNER_LC }}/jbs-nginx:ultra-4.0
